// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentApi.Data;

namespace PaymentApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20211201051131_Initial Migrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("PaymentApi.Models.ItemData", b =>
                {
                    b.Property<int>("paymentDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cardNumber")
                        .HasColumnType("text");

                    b.Property<string>("cardOwnerName")
                        .HasColumnType("text");

                    b.Property<string>("expirationDate")
                        .HasColumnType("text");

                    b.Property<string>("securityCode")
                        .HasColumnType("text");

                    b.HasKey("paymentDetailsId");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
